/**
 * The one-call config factory.
 *
 * Resolves plugins dynamically (Astro + Panda are optional peer deps), wires
 * the per-language presets together, and returns the flat-config array ready
 * to be the default export of `eslint.config.{js,mjs,ts}`.
 *
 * ```ts
 * // eslint.config.mjs
 * import { createConfig } from "@fullsnacklab/eslint-config";
 *
 * export default await createConfig({
 *   panda: {
 *     paths: { typesRoot: "./styled-system/dist/types" },
 *   },
 * });
 * ```
 *
 * @packageDocumentation
 */

import { existsSync } from "node:fs";
import path from "node:path";
import type { CreateConfigOptions, EslintConfig } from "./types.js";
import { createBase } from "./presets/base.js";
import { createJavaScript, type PandaPluginLike } from "./presets/javascript.js";
import { createTypeScript } from "./presets/typescript.js";
import { createAstro } from "./presets/astro.js";
import { createTheme } from "./presets/theme.js";
import { createPanda, buildPandaAstroPolicy } from "./presets/panda.js";
import { resolvePandaPaths } from "./panda/paths.js";

/**
 * Lazy import — Panda plugin is an optional peer dependency.
 *
 * Returns `null` when the plugin isn't installed, so the rest of the config
 * keeps working without it.
 */
async function tryLoadPandaPlugin(): Promise<PandaPluginLike | null> {
  try {
    const mod = await import("@pandacss/eslint-plugin");
    return (mod.default ?? mod) as PandaPluginLike;
  } catch {
    return null;
  }
}

/**
 * Probe whether the Panda catalog (generated by `panda codegen`) is present.
 *
 * We require at least `prop-type.d.ts` — that's the file that defines
 * `UtilityValues`, which is the source of truth for every other parser.
 */
function pandaCatalogExists(cwd: string = process.cwd()): boolean {
  const candidate = path.join(resolvePandaPaths({}, cwd).typesRoot, "prop-type.d.ts");
  return existsSync(candidate);
}

/**
 * Try to compute the Panda raw-CSS + pattern-fn policy.
 *
 * Behaviour:
 * - If the catalog files aren't on disk (consumer hasn't run `panda codegen`
 *   yet, or this isn't a Panda project at all), return `null`. The rest of the
 *   config still works.
 * - If the catalog exists but is malformed, surface a single helpful error.
 */
function tryResolvePandaAstroPolicy(
  options: CreateConfigOptions,
): ReturnType<typeof buildPandaAstroPolicy> | null {
  if (!pandaCatalogExists()) return null;
  try {
    return buildPandaAstroPolicy(options.panda);
  } catch (error) {
    throw new Error(
      `[@fullsnacklab/eslint-config] Panda preset failed to initialise. ` +
        `Run \`panda codegen\` and ensure \`styled-system/dist\` exists. ` +
        `Underlying error: ${(error as Error).message}`,
    );
  }
}

/**
 * Build the full flat config.
 *
 * Async because the Astro preset needs to dynamically detect whether
 * `eslint-plugin-astro` is installed. Most consumers will simply
 * `export default createConfig(...)` and let ESLint await the result; for
 * fully sync usage, `await` it at module top level.
 */
export async function createConfig(
  options: CreateConfigOptions = {},
): Promise<EslintConfig[]> {
  const wantsAstro = options.astro !== false;
  const panda = await tryLoadPandaPlugin();

  // Probe for Panda. Three states:
  //   1. Plugin not installed            → no Panda policies
  //   2. Plugin installed, no catalog    → no Panda policies (silently skipped)
  //   3. Plugin installed, catalog ok    → Panda policies wired in
  const pandaReady = Boolean(panda && pandaCatalogExists());
  const pandaAstroPolicy = pandaReady ? tryResolvePandaAstroPolicy(options) : null;

  const astro = wantsAstro
    ? await createAstro({ panda: pandaAstroPolicy ?? [] })
    : [];
  const js = createJavaScript({ panda: pandaReady ? panda! : undefined });
  const ts = createTypeScript({ panda: pandaReady ? panda! : undefined });
  const theme = createTheme();
  const pandaJs = pandaReady ? createPanda(options.panda) : [];

  const base = createBase({ ignores: options.ignores ? [...options.ignores] : [] });

  // Order matters — broader ignores go first, then file-type specific blocks.
  return [...base, ...astro, ...js, ...ts, ...theme, ...pandaJs];
}
